version: "3"
services:
  alice-web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
      - "49153:49153"
    command: npm run start

  acme-web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4201:4201"
      - "49153:49153"
    command: npm run faber

  faber-web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4202:4202"
      - "49153:49153"
    command: npm run acme
